#!/usr/bin/env bash
set -euo pipefail

ok() { printf '  \033[32m✓\033[0m %s\n' "$1"; }
ng() { printf '  \033[31m✗\033[0m %s\n' "$1"; }

FAIL=0

is_autogen_path() {
    local f="$1"
    case "$f" in
        *.terraform.lock.hcl) return 0 ;;
        */.terraform/*) return 0 ;;
        *Cargo.lock) return 0 ;;
        *package-lock.json) return 0 ;;
        *pnpm-lock.yaml) return 0 ;;
        *yarn.lock) return 0 ;;
        *poetry.lock) return 0 ;;
        *uv.lock) return 0 ;;
        *Pipfile.lock) return 0 ;;
        *composer.lock) return 0 ;;
        *go.sum) return 0 ;;
        *.generated.*) return 0 ;;
        *.gen.*) return 0 ;;
        */vendor/*) return 0 ;;
        */node_modules/*) return 0 ;;
    esac
    return 1
}

is_autogen_header() {
    local f="$1"
    head -5 "$f" 2>/dev/null | grep -qiE 'maintained automatically|do not edit|automatically generated|generated by|@generated|autogenerated'
}

while IFS= read -r file; do
    [[ -f "$file" ]] || continue
    if is_autogen_path "$file"; then continue; fi
    if is_autogen_header "$file"; then continue; fi
    ext="${file##*.}"

    if head -3 "$file" 2>/dev/null | grep -qE "managed-by:|AUTO-GENERATED|DO NOT EDIT"; then
        continue
    fi

    case "$file" in
        node_modules/*|vendor/*|public/build/*|public/vendor/*|dist/*|bootstrap/cache/*) continue ;;
    esac

    case "$ext" in
        rs|ts|tsx|js|jsx|mts|cts|mjs|cjs)
            pattern='^\s*//' ;;
        php)
            pattern='^\s*//' ;;
        sh|bash|tf|hcl|py)
            pattern='^\s*#' ;;
        *)
            continue ;;
    esac

    hits=$(grep -nE "$pattern" "$file" \
        | grep -v ':[[:space:]]*#!' \
        | grep -v ':[[:space:]]*#\[' \
        | grep -vE ':[[:space:]]*(///|//!|/\*\*|/\*!|\*/|\* )' \
        || true)

    if [[ -n "$hits" ]]; then
        ng "주석 발견: $file"
        echo "$hits" | head -3 | sed 's/^/    /'
        FAIL=1
    fi
done < <(git diff --cached --name-only --diff-filter=ACM)

if [[ "$FAIL" != "0" ]]; then
    exit 1
fi
ok "주석 없음"
