import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { collectAllSkills } from './sources';
import { readConfig } from './config';

const START = '<!-- vibeskills-START -->';
const END = '<!-- vibeskills-END -->';
// Legacy markers from the old "ccskills" brand. Detected so existing user blocks
// get replaced in-place; new writes always use the current markers above.
const LEGACY_START = '<!-- ccskills-START -->';
const LEGACY_END = '<!-- ccskills-END -->';
const ANY_BLOCK_RE = new RegExp(
  `(?:${START}|${LEGACY_START})[\\s\\S]*?(?:${END}|${LEGACY_END})`
);
const ANY_BLOCK_WITH_NL_RE = new RegExp(
  `\\n?(?:${START}|${LEGACY_START})[\\s\\S]*?(?:${END}|${LEGACY_END})\\n?`
);

interface Target {
  path: string;
  label: string;
}

export const TARGETS: Record<string, Target> = {
  'AGENTS.md': { path: 'AGENTS.md', label: 'AGENTS.md' },
  'CLAUDE.md': { path: 'CLAUDE.md', label: 'CLAUDE.md' },
  'GEMINI.md': { path: 'GEMINI.md', label: 'GEMINI.md' },
  '.cursor/rules': { path: '.cursor/rules', label: 'Cursor Rules' },
  '.windsurfrules': { path: '.windsurfrules', label: 'Windsurf' },
  '.clinerules': { path: '.clinerules', label: 'Cline' },
  '.github/copilot-instructions.md': { path: '.github/copilot-instructions.md', label: 'Copilot' }
};

export function renderBlock(format = 'ref'): string {
  const skills = collectAllSkills({});
  if (!skills.length) return `${START}\n## Agent Skills\n\n_No skills installed._\n${END}`;
  let body: string;
  if (format === 'compact') {
    body = skills
      .map(s => `- **${s.name}**${s.info.description ? ': ' + s.info.description.slice(0, 100) : ''}`)
      .join('\n');
  } else if (format === 'ref') {
    body =
      '| Skill | Scope | Description |\n|---|---|---|\n' +
      skills
        .map(
          s =>
            `| **${s.name}** | ${s.source.label}/${s.source.scope} | ${(s.info.description || '').replace(/\|/g, '\\|').slice(0, 160)} |`
        )
        .join('\n');
  } else if (format === 'full') {
    body = skills
      .map(s => {
        const cat = (s.info.categories || []).join(', ');
        return `### ${s.name}\n\n- **Source**: ${s.source.label} / ${s.source.scope}\n- **Path**: \`${s.dir}\`\n${cat ? `- **Categories**: ${cat}\n` : ''}${s.info.description ? `\n${s.info.description}\n` : ''}${s.info.whenToUse ? `\n**When to use**: ${s.info.whenToUse}\n` : ''}`;
      })
      .join('\n\n');
  } else {
    body = skills.map(s => `- \`${s.name}\` — ${s.info.description || '(no description)'}`).join('\n');
  }
  return `${START}\n## Agent Skills\n\n> Auto-generated by Vibecode Skills Viewer. Do not edit between the markers.\n\n${body}\n${END}`;
}

export function injectBlock(content: string, block: string): string {
  if (ANY_BLOCK_RE.test(content)) {
    return content.replace(ANY_BLOCK_RE, block);
  }
  if (!content.trim()) return block + '\n';
  return content.trimEnd() + '\n\n' + block + '\n';
}

function getWorkspaceRoot(): string | null {
  const ws = vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders[0];
  return ws ? ws.uri.fsPath : null;
}

export async function syncTarget(targetKey: string, formatOverride?: string): Promise<string> {
  const ws = getWorkspaceRoot();
  if (!ws) throw new Error('No workspace open');
  const target = TARGETS[targetKey];
  if (!target) throw new Error(`Unknown target: ${targetKey}`);
  const format = formatOverride || readConfig().instructionFormat;
  const filePath = path.join(ws, target.path);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const cur = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  const block = renderBlock(format);
  const next = injectBlock(cur, block);
  if (cur !== next) fs.writeFileSync(filePath, next, 'utf8');
  return filePath;
}

export async function syncAll(): Promise<string[]> {
  const written: string[] = [];
  for (const k of Object.keys(TARGETS)) {
    try {
      written.push(await syncTarget(k));
    } catch {}
  }
  return written;
}

export async function removeBlock(targetKey: string): Promise<void> {
  const ws = getWorkspaceRoot();
  if (!ws) return;
  const target = TARGETS[targetKey];
  const filePath = path.join(ws, target.path);
  if (!fs.existsSync(filePath)) return;
  const cur = fs.readFileSync(filePath, 'utf8');
  if (!ANY_BLOCK_RE.test(cur)) return;
  const next = cur.replace(ANY_BLOCK_WITH_NL_RE, '');
  fs.writeFileSync(filePath, next, 'utf8');
}
