// AUTO-GENERATED by tools/sync-eslint.mjs from tools/eslint-config-master.mjs.
// DO NOT EDIT IN PLACE. Edit the master, then run `node tools/sync-eslint.mjs`.
// Per-extension overrides go in `eslint.config.local.mjs` next to this file
// (auto-imported and merged below if present).


import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      '*.vsix',
      'icons/**',
      'resources/**',
      'tests/setup.cjs',
      'tests/_mocks/**'
    ]
  },
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module'
      }
    },
    rules: {
      // TS — relaxed where the codebase has good reasons
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none'
      }],
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',

      // Code quality
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'eqeqeq': ['error', 'smart'],
      'prefer-const': 'warn',
      'no-var': 'error',
      'no-duplicate-imports': 'error'
    }
  },
  {
    // Webview client + ext-side panel use the outFile + sections + ambient-contracts
    // pattern (see vibecode-webview-architecture skill). Triple-slash references and
    // namespaces are intentional, not lint debt.
    files: [
      'src/views/**/panel.ts',
      'src/views/**/client/**/*.ts',
      'src/webview/**/*.ts',
      'src/preview/client/**/*.ts',
      'src/settings/client/**/*.ts'
    ],
    rules: {
      '@typescript-eslint/triple-slash-reference': 'off',
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-unused-vars': 'off'
    }
  }
);

// Per-extension overrides — create eslint.config.local.mjs to extend.
// import localOverrides from './eslint.config.local.mjs';   // optional
