#!/usr/bin/env node
// Propagate tools/eslint-config-master.mjs → every vibecode-*/eslint.config.mjs.
// Each extension stays self-contained (its own config file) so per-ext lint
// commands work without a root install. Local per-ext extras (if any) live in
// `eslint.config.local.mjs` next to the synced file — the synced file imports
// it when present and merges.
//
// Usage:
//   node tools/sync-eslint.mjs          # write
//   node tools/sync-eslint.mjs --check  # exit 1 if anything would change

import { promises as fs } from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MASTER = path.join(__dirname, 'eslint-config-master.mjs');
const CHECK = process.argv.includes('--check');

const HEADER = `// AUTO-GENERATED by tools/sync-eslint.mjs from tools/eslint-config-master.mjs.
// DO NOT EDIT IN PLACE. Edit the master, then run \`node tools/sync-eslint.mjs\`.
// Per-extension overrides go in \`eslint.config.local.mjs\` next to this file
// (auto-imported and merged below if present).
`;

const FOOTER = `
// Per-extension overrides — create eslint.config.local.mjs to extend.
// import localOverrides from './eslint.config.local.mjs';   // optional
`;

async function listExtensions() {
  const entries = await fs.readdir(ROOT, { withFileTypes: true });
  const out = [];
  for (const e of entries) {
    if (!e.isDirectory() || !e.name.startsWith('vibecode-')) continue;
    const pkg = path.join(ROOT, e.name, 'package.json');
    try { await fs.access(pkg); } catch { continue; }
    out.push(e.name);
  }
  return out.sort();
}

async function writeIfChanged(file, content) {
  let prev = '';
  try { prev = await fs.readFile(file, 'utf8'); } catch {}
  if (prev === content) return false;
  if (CHECK) {
    console.error(`[sync-eslint] would change: ${path.relative(ROOT, file)}`);
    return true;
  }
  await fs.writeFile(file, content);
  console.log(`[sync-eslint] wrote: ${path.relative(ROOT, file)}`);
  return true;
}

async function main() {
  const master = await fs.readFile(MASTER, 'utf8');
  // Strip the master's leading comment block — replace with the AUTO-GENERATED header.
  const stripped = master.replace(/^(\/\/[^\n]*\n)+/, '');
  const synced = HEADER + '\n' + stripped + FOOTER;

  let anyChanged = false;
  for (const ext of await listExtensions()) {
    const target = path.join(ROOT, ext, 'eslint.config.mjs');
    const changed = await writeIfChanged(target, synced);
    anyChanged = anyChanged || changed;
  }

  if (CHECK && anyChanged) process.exit(1);
  if (!anyChanged) console.log('[sync-eslint] up to date.');
}

main().catch(err => { console.error(err); process.exit(1); });
